// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbnomhmtkqnktnyxlcpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxibm9taG10a3Fua3RueXhsY3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0OTcxNTksImV4cCI6MjA4ODA3MzE1OX0.8gFmX2CSaVsGDBwX2VetW2HHyHvtdjQdJim5xsmlefI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});